---
- name: Create IPython profile.
  command: ipython profile create

- name: Start IPython notebook server.
  command: ipython notebook


#- name: IPython -- Change IPython owner.
#file: path=/home/steve/.ipython owner=steve recurse=yes state=directory

#- name: IPython -- Automatically import modules.
#lineinfile: dest=/home/steve/.ipython/profile_default/ipython_config.py 
#regexp="^c.InteractiveShellApp.exec_lines = " 
              #line="c.InteractiveShellApp.exec_lines = ['import numpy, scipy']"

#- name: IPython -- qt4 backend.
#lineinfile: dest=/home/steve/.ipython/profile_default/ipython_config.py 
#regexp="^c.InteractiveShellApp.pylab = "
#line="c.InteractiveShellApp.pylab = 'qt4'"
